openapi: "3.0.1"
info:
  title: learn express and swagger
  description: a course segment about writing docs
  version: 1.1.0
  contact:
    email: lucky@bigwings.us
    url: "google.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https